/* SPDX-License-Identifier: MIT */
#ifndef GENERATED_FIXTURE_H_
#define GENERATED_FIXTURE_H_
#define FIXTURE_CRC32_INITIATOR UINT32_C(0x11223344)
#define FIXTURE_CRC32_REFLECTOR UINT32_C(0x55667788)
#define FIXTURE_CONFIG_ID 3U
#define FIXTURE_PATTERN "CS"
#define FIXTURE_LOG_CONSOLE APP_LOG_LEVEL_DBG
#define FIXTURE_LOG_PROTOCOL APP_LOG_LEVEL_INF
#endif
