/* SPDX-License-Identifier: MIT */
#include "host_link_names.h"
#include "cs_protocol/cs_protocol_packets.h"

#define UNKNOWN "?"

#define NAME_OF(table, value) \
	((value) < sizeof(table) / sizeof((table)[0]) && (table)[value] ? (table)[value] : UNKNOWN)

static const char *const state_names[] = {
    [CS_PROTOCOL_CLIENT_STATE_LINK_CONNECTING] = "LINK_CONNECTING",
	[CS_PROTOCOL_CLIENT_STATE_IDLE] = "IDLE",
	[CS_PROTOCOL_CLIENT_STATE_CONFIGURED] = "CONFIGURED",
	[CS_PROTOCOL_CLIENT_STATE_SCANNING] = "SCANNING",
	[CS_PROTOCOL_CLIENT_STATE_ADVERTISING] = "ADVERTISING",
	[CS_PROTOCOL_CLIENT_STATE_LINK_CONNECTED] = "LINK_CONNECTED",
	[CS_PROTOCOL_CLIENT_STATE_RAS_READY] = "RAS_READY",
	[CS_PROTOCOL_CLIENT_STATE_RUNNING] = "RUNNING",
	[CS_PROTOCOL_CLIENT_STATE_STOPPED] = "STOPPED",
	[CS_PROTOCOL_CLIENT_STATE_LINK_LOST] = "LINK_LOST",
	[CS_PROTOCOL_CLIENT_STATE_LINK_DISCONNECTED] = "LINK_DISCONNECTED",
	[CS_PROTOCOL_CLIENT_STATE_ERROR] = "ERROR",
};

static const char *const mode_names[] = {
	[CS_PROTOCOL_MODE_CS_INITIATOR] = "CS_INITIATOR",
	[CS_PROTOCOL_MODE_CS_REFLECTOR] = "CS_REFLECTOR",
	[CS_PROTOCOL_MODE_RADIO_TX_TEST] = "RADIO_TX_TEST",
};

static const char *const status_names[] = {
	[CS_PROTOCOL_STATUS_OK] = "OK",
	[CS_PROTOCOL_STATUS_REJECTED] = "REJECTED",
	[CS_PROTOCOL_STATUS_UNSUPPORTED] = "UNSUPPORTED",
	[CS_PROTOCOL_STATUS_BAD_STATE] = "BAD_STATE",
	[CS_PROTOCOL_STATUS_INVALID_FRAME] = "INVALID_FRAME",
	[CS_PROTOCOL_STATUS_VERSION] = "VERSION",
	[CS_PROTOCOL_STATUS_FAILED] = "FAILED",
	[CS_PROTOCOL_STATUS_CONFIG_MISMATCH] = "CONFIG_MISMATCH",
};

static const char *const reason_names[] = {
    [CS_PROTOCOL_REASON_CS_SECURITY_FAILED] = "CS_SECURITY_FAILED",
    [CS_PROTOCOL_REASON_CS_CONFIG_FAILED] = "CS_CONFIG_FAILED",
    [CS_PROTOCOL_REASON_RAS_DISCOVERY_FAILED] = "RAS_DISCOVERY_FAILED",
    [CS_PROTOCOL_REASON_SECURITY_FAILED] = "SECURITY_FAILED",
    [CS_PROTOCOL_REASON_CONNECT_FAILED] = "CONNECT_FAILED",
    [CS_PROTOCOL_REASON_ADVERTISE_FAILED] = "ADVERTISE_FAILED",
    [CS_PROTOCOL_REASON_SCAN_FAILED] = "SCAN_FAILED",
	[CS_PROTOCOL_REASON_NONE] = "NONE",
	[CS_PROTOCOL_REASON_NOT_CONNECTED] = "NOT_CONNECTED",
	[CS_PROTOCOL_REASON_MODE_MISMATCH] = "MODE_MISMATCH",
	[CS_PROTOCOL_REASON_VALUE_OUT_OF_RANGE] = "VALUE_OUT_OF_RANGE",
	[CS_PROTOCOL_REASON_NONZERO_PADDING] = "NONZERO_PADDING",
	[CS_PROTOCOL_REASON_MISSING_CONFIG] = "MISSING_CONFIG",
	[CS_PROTOCOL_REASON_MISSING_PATTERNS] = "MISSING_PATTERNS",
	[CS_PROTOCOL_REASON_BUSY] = "BUSY",
	[CS_PROTOCOL_REASON_LINK_ACTIVE] = "LINK_ACTIVE",
	[CS_PROTOCOL_REASON_STOP_TIMEOUT] = "STOP_TIMEOUT",
	[CS_PROTOCOL_REASON_RAS_NO_REALTIME] = "RAS_NO_REALTIME",
	[CS_PROTOCOL_REASON_TEST_COMPLETE] = "TEST_COMPLETE",
	[CS_PROTOCOL_REASON_INTERRUPTED] = "INTERRUPTED",
	[CS_PROTOCOL_REASON_PEER_IPT_UNSUPPORTED] = "PEER_IPT_UNSUPPORTED",
};

/* Host commands start at SET_OPERATION_MODE (0x0100). */
static const char *const command_names[] = {
    [CS_PROTOCOL_PACKET_ADVERTISE_START - 0x0100] = "ADVERTISE_START",
    [CS_PROTOCOL_PACKET_PEER_CONNECT - 0x0100] = "PEER_CONNECT",
    [CS_PROTOCOL_PACKET_SCAN_START - 0x0100] = "SCAN_START",
    [CS_PROTOCOL_PACKET_SET_DEVICE_NAME - 0x0100] = "SET_DEVICE_NAME",
	[CS_PROTOCOL_PACKET_SET_PEER_DATA - 0x0100] = "SET_PEER_DATA",
	[CS_PROTOCOL_PACKET_SET_LOG_CONFIG - 0x0100] = "SET_LOG_CONFIG",
	[CS_PROTOCOL_PACKET_SET_T_PM - 0x0100] = "SET_T_PM",
	[CS_PROTOCOL_PACKET_SET_OPERATION_MODE - 0x0100] = "SET_OPERATION_MODE",
	[CS_PROTOCOL_PACKET_SET_CS_INITIATOR_CONFIG - 0x0100] = "SET_CS_INITIATOR_CONFIG",
	[CS_PROTOCOL_PACKET_SET_CS_REFLECTOR_CONFIG - 0x0100] = "SET_CS_REFLECTOR_CONFIG",
	[CS_PROTOCOL_PACKET_SET_RADIO_TX_TEST_CONFIG - 0x0100] = "SET_RADIO_TX_TEST_CONFIG",
	[CS_PROTOCOL_PACKET_SET_PERIPHERAL_PATTERNS - 0x0100] = "SET_PERIPHERAL_PATTERNS",
	[CS_PROTOCOL_PACKET_APPLY_CONFIG - 0x0100] = "APPLY_CONFIG",
	[CS_PROTOCOL_PACKET_CONNECT - 0x0100] = "CONNECT",
	[CS_PROTOCOL_PACKET_START - 0x0100] = "START",
	[CS_PROTOCOL_PACKET_STOP - 0x0100] = "STOP",
	[CS_PROTOCOL_PACKET_CLOSE_SESSION - 0x0100] = "CLOSE_SESSION",
	[CS_PROTOCOL_PACKET_GET_CONFIG - 0x0100] = "GET_CONFIG",
	[CS_PROTOCOL_PACKET_LINK_DISCONNECT - 0x0100] = "LINK_DISCONNECT",
};

const char *host_link_state_name(uint8_t state) {
	return NAME_OF(state_names, state);
}

const char *host_link_mode_name(uint8_t mode) {
	return mode == CS_PROTOCOL_MODE_NONE ? "NONE" : NAME_OF(mode_names, mode);
}

const char *host_link_status_name(uint8_t status) {
	return NAME_OF(status_names, status);
}

const char *host_link_reason_name(uint8_t reason) {
	return NAME_OF(reason_names, reason);
}

const char *host_link_command_name(uint16_t type) {
	return type < 0x0100U ? UNKNOWN : NAME_OF(command_names, (unsigned int)(type - 0x0100U));
}
