/* SPDX-License-Identifier: MIT */
/* Antenna selections against the local antenna count (SET_CS_*_CONFIG). */
#undef NDEBUG
#include "host_link/host_link_config.h"
#include <assert.h>
#include <stdio.h>

#define INI CS_PROTOCOL_MODE_CS_INITIATOR
#define REF CS_PROTOCOL_MODE_CS_REFLECTOR
#define CHECK host_link_config_check_antennas

int main(void) {
	/* One antenna: only A1:B1 and antenna 1, repetitive or no recommendation. */
	assert(CHECK(INI, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_REPETITIVE, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A1_B1, 1) == 0);
	assert(CHECK(REF, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_NO_RECOMMENDATION, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A1_B1, 1) == 0);
	assert(CHECK(INI, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_ONE, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A1_B1, 1) == 0);
	assert(CHECK(INI, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_TWO, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A1_B1, 1) == -ERANGE);
	assert(CHECK(REF, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_FOUR, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A1_B1, 1) == -ERANGE);

	/* The peer's side of the tone configuration is not checked. */
	assert(CHECK(INI, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_ONE, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A1_B4, 1) == 0);
	assert(CHECK(INI, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_ONE, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A2_B1, 1) == -ERANGE);
	assert(CHECK(REF, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_ONE, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A4_B1, 1) == 0);
	assert(CHECK(REF, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_ONE, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A1_B2, 1) == -ERANGE);
	assert(CHECK(INI, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_ONE, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A2_B2, 1) == -ERANGE);
	assert(CHECK(REF, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_ONE, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A2_B2, 1) == -ERANGE);

	/* More antennas widen both limits. */
	assert(CHECK(INI, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_TWO, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A2_B2, 2) == 0);
	assert(CHECK(REF, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_TWO, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A2_B2, 2) == 0);
	assert(CHECK(INI, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_THREE, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A2_B2, 2) == -ERANGE);
	assert(CHECK(INI, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_FOUR, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A4_B1, 4) == 0);
	assert(CHECK(REF, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_FOUR, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A1_B4, 4) == 0);

	/* Undefined encodings are invalid whatever the antenna count. */
	assert(CHECK(INI, 0x00, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A1_B1, 4) == -EINVAL);
	assert(CHECK(INI, 0x05, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A1_B1, 4) == -EINVAL);
	assert(CHECK(INI, 0xFD, CS_PROTOCOL_CONFIG_TONE_ANTENNA_A1_B1, 4) == -EINVAL);
	assert(CHECK(REF, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_ONE, 0x08, 4) == -EINVAL);
	assert(CHECK(CS_PROTOCOL_MODE_RADIO_TX_TEST, CS_PROTOCOL_CONFIG_SYNC_ANTENNA_ONE,
	             CS_PROTOCOL_CONFIG_TONE_ANTENNA_A1_B1, 4) == -EINVAL);

	printf("host_link antennas: OK\n");
	return 0;
}
