# SPDX-License-Identifier: MIT
# Compiler flags of the cs_roles native tests, sourced by run.sh. The CONFIG_
# values are the Kconfig defaults (common/libs/Kconfig, NCS RAS).
: "${ZEPHYR_BASE:?set ZEPHYR_BASE to the NCS zephyr directory}"
NCS_NRF=${NCS_NRF:-$ZEPHYR_BASE/../nrf}
cs_roles_flags="-std=gnu11 -Wall -Wextra -Werror -fsanitize=address,undefined
    -DCONFIG_ARCH_POSIX -DCONFIG_ATOMIC_OPERATIONS_BUILTIN -DCONFIG_LITTLE_ENDIAN=1 -D__noinit= -DCONFIG_SYS_CLOCK_TICKS_PER_SEC=32768 -DCONFIG_SYS_CLOCK_MAX_TIMEOUT_DAYS=365
    -DCONFIG_BT_CHANNEL_SOUNDING=1 -DCONFIG_BT_RAS_MAX_ANTENNA_PATHS=4 -DCONFIG_BT_RAS_MODE_3_SUPPORTED=1
    -DCONFIG_APP_CS_ROLES_INITIATOR=1 -DCONFIG_APP_CS_ROLES_REFLECTOR=1
    -DCONFIG_APP_CS_ROLES_THREAD_STACK_SIZE=3072 -DCONFIG_APP_CS_ROLES_THREAD_PRIORITY=7
    -DCONFIG_APP_CS_ROLES_MSG_QUEUE_DEPTH=16 -DCONFIG_APP_CS_ROLES_EVENT_STACK_SIZE=2048
    -DCONFIG_APP_CS_ROLES_EVENT_PRIORITY=8 -DCONFIG_APP_CS_ROLES_EVENT_QUEUE_DEPTH=24
    -DCONFIG_APP_CS_ROLES_EVENT_RESERVE=8 -DCONFIG_APP_CS_ROLES_RAS_MAX_SUBEVENTS=32
    -DCONFIG_APP_CS_ROLES_SETUP_TIMEOUT_MS=10000 -DCONFIG_APP_CS_ROLES_STOP_TIMEOUT_MS=2000
    -DCONFIG_APP_CS_ROLES_STOP_RAS_TIMEOUT_MS=2000 -DCONFIG_APP_CS_ROLES_LINK_RESTART_DELAY_MS=1000
    -Itests/cs_roles/include -Icommon/libs -I$ZEPHYR_BASE/include -I$NCS_NRF/include"
