/* Generated by ble-channel-sounding 0.1.0; 2026-09-15T15:25:52.873945+00:00 */
/* Configuration name: cs_generated_config */
/* Operation mode: CS reflector; IPT: requested (set by the initiator) */
#include <cs_generated_config/cs_generated_config.h>
#include <cs_utils/cs_config.h>

const uint32_t cs_generated_config_crc32_reflector = 0x03e36c1cU;

int cs_generated_config_reflector(struct cs_reflector_config *config) {
    int err = cs_reflector_config_get_default(config);
    if (err) return err;
    const struct cs_config_connection connection = {
        .interval_min = 6,
        .interval_max = 50,
        .latency = 0,
        .timeout = 400,
    };
    err = cs_reflector_config_set_connection(config, &connection);
    if (err) return err;
    const struct cs_config_default_settings default_settings = {
        .cs_sync_antenna_selection = CS_CONFIG_SYNC_ANTENNA_REPETITIVE,
        .max_tx_power = 20,
    };
    err = cs_reflector_config_set_default_settings(config, &default_settings);
    if (err) return err;
    const struct cs_config_procedure procedure = {
        .max_procedure_len = 16,
        .min_procedure_interval = 1,
        .max_procedure_interval = 1,
        .max_procedure_count = 0,
        .min_subevent_len = 5000,
        .max_subevent_len = 5000,
        .tone_antenna_config_selection = CS_CONFIG_TONE_ANTENNA_A1_B1,
        .phy = CS_CONFIG_PROCEDURE_PHY_1M,
        .tx_power_delta = CS_CONFIG_TX_POWER_DELTA_NONE,
        .preferred_peer_antenna = 1,
        .snr_control_initiator = CS_CONFIG_SNR_CONTROL_NOT_USED,
        .snr_control_reflector = CS_CONFIG_SNR_CONTROL_NOT_USED,
    };
    err = cs_reflector_config_set_procedure(config, &procedure);
    if (err) return err;
    err = cs_reflector_config_set_config_id(config, 0);
    if (err) return err;
    return 0;
}

int cs_generated_config_patterns(const char *const **patterns, size_t *count) {
    if (!patterns || !count) return -22;
    *patterns = 0;
    *count = 0;
    return 0;
}

const char *cs_generated_config_device_name(void) {
    return NULL;
}

/* CS_PLANNER_SCENARIO_JSON
{
  "schema_version": 1,
  "connection": {
    "interval_min": 6,
    "interval_max": 50,
    "interval": 20,
    "latency": 0,
    "timeout": 400,
    "activity_us": 1000
  },
  "configuration": {
    "id": 0,
    "mode": 2,
    "min_main_mode_steps": 1,
    "max_main_mode_steps": 4,
    "main_mode_repetition": 0,
    "mode_0_steps": 2,
    "role": 1,
    "rtt_type": 0,
    "cs_sync_phy": 2,
    "channel_map_repetition": 1,
    "channel_selection_type": 0,
    "ch3c_shape": 0,
    "ch3c_jump": 2,
    "cs_enhancements_1": 1,
    "t_ip1_time_us": 10,
    "t_ip2_time_us": 10,
    "t_fcs_time_us": 50,
    "t_pm_time_us": 10,
    "channel_map": "fcff7ffcffffffffff1f"
  },
  "procedure": {
    "config_id": 0,
    "state": 1,
    "tone_antenna_config_selection": 0,
    "selected_tx_power": 0,
    "subevent_len": 5000,
    "subevents_per_event": 3,
    "subevent_interval": 10,
    "event_interval": 1,
    "procedure_interval": 1,
    "procedure_count": 0,
    "max_procedure_len": 16
  },
  "target_steps": 72,
  "main_steps": 4,
  "t_sw_us": 2,
  "t_sw_ipt_us": 2,
  "event_offset_us": 1500,
  "preview_count": 3,
  "provenance": "Hypothetical configuration and schedule",
  "channel_seed": 1,
  "host_settings": {
    "gap_role": 1,
    "cs_sync_antenna_selection": 254,
    "max_tx_power": 20,
    "phy": 1,
    "tx_power_delta": -128,
    "preferred_peer_antenna": 1,
    "snr_control_initiator": 255,
    "snr_control_reflector": 255,
    "creation_context": 1,
    "peripheral_patterns": [
      "CS"
    ]
  }
}

*/
