"""cs_planner C export: identical to the cs-app export, compiles, and round-trips."""

from dataclasses import fields, replace
import json
from pathlib import Path
import shutil
import subprocess
import unittest

from cs_planner.export_c import HOST_DEFAULTS, config_crc32, config_values, document, generate, load_document
from cs_planner.model import Scenario

PYTHON_DIR = Path(__file__).resolve().parents[1]
PLAN_FIXTURE = Path(__file__).resolve().parent / "data" / "cs-plan.json"


def body(source):
    """Source without the first line, which carries the generator name and time."""
    return source.split("\n", 1)[1]


class ExportTests(unittest.TestCase):
    def cases(self):
        s = Scenario()
        ipt = replace(s, configuration=replace(s.configuration, cs_enhancements_1=1, channel_selection_type=1, ch3c_jump=3))
        yield s, {"peripheral_patterns": ["CS"]}
        yield ipt, {"gap_role": 1, "peripheral_patterns": ["R"], "phy": 2, "snr_control_initiator": 2, "device_name": "Tag ä"}
        yield replace(s, provenance="quote */ comment"), {"peripheral_patterns": ['ä"*/', "B"], "tx_power_delta": 3}
        yield load_document(PLAN_FIXTURE.read_text(encoding="utf-8"))

    def test_matches_cs_app_configuration_and_crc(self):
        from cs_app.planner.bridge import config_packet
        from cs_app.planner.model import loads as app_loads
        from cs_app.protocol.config import ClientConfig
        from cs_app.protocol.packets import (DeviceNamePacket, OperationMode,
                                             PeripheralPatternsPacket)
        for scenario, host in self.cases():
            app_scenario = app_loads(document(scenario))
            for role in ("initiator", "reflector", "both"):
                ours = generate(scenario, host, role=role)
                self.assertEqual(set(ours), {"initiator", "reflector"} if role == "both" else {role})
                for selected in ours:
                    self.assertTrue(ours[selected].startswith("/* Generated by cs_planner; "))
                    self.assertNotIn("cs_initiator_config_set_peer_data", ours[selected])
                    self.assertNotIn("cs_generated_config_log(", ours[selected])
                    mode = (OperationMode.CS_INITIATOR if selected == "initiator"
                            else OperationMode.CS_REFLECTOR)
                    expected_host = {**host}
                    if role == "both":
                        expected_host["gap_role"] = 0 if selected == "initiator" else 1
                    packet = config_packet(app_scenario, expected_host, mode)
                    patterns = (expected_host.get("peripheral_patterns", [])
                                if expected_host.get("gap_role", 0) == 0 else [])
                    device_name = expected_host.get("device_name") or ""
                    complete = ClientConfig(mode, packet,
                                            PeripheralPatternsPacket.from_patterns(patterns) if patterns else None,
                                            DeviceNamePacket.from_name(device_name) if device_name else None)
                    self.assertIn(f"const uint32_t cs_generated_config_crc32_{selected} = 0x{complete.crc32():08x}U;",
                                  ours[selected])
            for role, mode in (("initiator", OperationMode.CS_INITIATOR), ("reflector", OperationMode.CS_REFLECTOR)):
                packet = config_packet(app_scenario, host, mode)
                self.assertEqual(list(config_values(scenario, host, role).values()),
                                 [getattr(packet, f.name) for f in fields(packet)])

    def test_runtime_overrides_are_ignored_and_not_saved(self):
        s = Scenario()
        host = {"gap_role": 1, "peer_data": 1, "log": {"console": 4, "host": 4}}
        baseline = generate(s, {"gap_role": 1}, role="initiator")["initiator"]
        overridden = generate(s, host, role="initiator")["initiator"]
        self.assertEqual(body(baseline), body(overridden))
        saved = json.loads(document(s, host))
        self.assertNotIn("peer_data", saved["host_settings"])
        self.assertNotIn("log", saved["host_settings"])
        self.assertNotEqual(config_crc32("initiator", config_values(s, host, "initiator"),
                                        peer_data=1, log={"console": 4, "host": 4}),
                            config_crc32("initiator", config_values(s, host, "initiator")))

    def test_crc_matches_client_config(self):
        from cs_app.planner.bridge import config_packet
        from cs_app.planner.model import loads as app_loads
        from cs_app.protocol.config import ClientConfig
        from cs_app.protocol.packets import DeviceNamePacket, OperationMode, PeripheralPatternsPacket
        s = Scenario()
        host = {"peripheral_patterns": ["CS", "Tag"], "device_name": "Board"}
        packet = config_packet(app_loads(document(s)), host, OperationMode.CS_INITIATOR)
        expected = ClientConfig(OperationMode.CS_INITIATOR, packet, PeripheralPatternsPacket.from_patterns(["CS", "Tag"]),
                                DeviceNamePacket.from_name("Board")).crc32()
        self.assertEqual(config_crc32("initiator", config_values(s, host, "initiator"), ["CS", "Tag"], "Board"), expected)

    def test_negotiated_request_ranges_match_cs_app(self):
        from cs_app.planner.bridge import apply_packet, config_packet
        from cs_app.planner.model import loads as app_loads
        from cs_app.protocol.packets import OperationMode
        s = app_loads(document(Scenario()))
        request = replace(config_packet(s, {}, OperationMode.CS_INITIATOR), min_subevent_len=5000, max_subevent_len=9000,
                          min_procedure_interval=10, max_procedure_interval=40, max_tx_power=-8)
        s, host = apply_packet(s, dict(HOST_DEFAULTS), request)
        s, host = apply_packet(s, host, replace(s.configuration, t_ip1_time_us=80))
        scenario, loaded = load_document(document(s, host))
        self.assertEqual(config_values(scenario, loaded, "initiator"),
                         {k: getattr(config_packet(s, host, OperationMode.CS_INITIATOR), k)
                          for k in config_values(scenario, loaded, "initiator")})

    def test_round_trip_role_ipt_and_refusals(self):
        s = Scenario()
        s = replace(s, configuration=replace(s.configuration, role=1, cs_enhancements_1=1))
        output = generate(s, {"peripheral_patterns": ["CS"]}, role="both")
        for role, source in output.items():
            recovered, settings = load_document(source)
            self.assertEqual(recovered.configuration.role, 0 if role == "initiator" else 1)
            self.assertEqual(settings["gap_role"], 0 if role == "initiator" else 1)
        self.assertIn("cs_initiator_config_enable_ipt(config)", output["initiator"])
        self.assertNotIn("enable_ipt", output["reflector"])
        self.assertEqual(set(json.loads(document(Scenario()))["host_settings"]), {*HOST_DEFAULTS, "peripheral_patterns"})
        with self.assertRaises(ValueError):
            generate(Scenario(), role="initiator")  # central without prefixes
        with self.assertRaises(ValueError):
            generate(replace(Scenario(), main_steps=0), {"gap_role": 1})
        with self.assertRaises(ValueError):
            generate(Scenario(), {"gap_role": 1, "device_name": "x" * 33})
        with self.assertRaises(ValueError):
            generate(Scenario(), {"gap_role": 1, "max_tx_power": 200})
        a1_b2 = replace(Scenario(), procedure=replace(Scenario().procedure, tone_antenna_config_selection=4))
        with self.assertRaisesRegex(ValueError, "CS initiator: .*Set at least 2 bits"):
            generate(a1_b2, {"gap_role": 1}, role="initiator")
        # The reflector record gets the same mask: at least the one initiator antenna of A1:B2.
        generate(a1_b2, {"preferred_peer_antenna": 3, "peripheral_patterns": ["CS"]}, role="both")

    def test_generated_source_compiles(self):
        compiler = shutil.which("cc")
        if not compiler:
            self.skipTest("No host C compiler")
        root = PYTHON_DIR.parent
        for source in generate(Scenario(), {"peripheral_patterns": ["CS"], "device_name": "Tag"}, role="both").values():
            result = subprocess.run([compiler, "-x", "c", "-std=c11", "-Werror", "-fsyntax-only",
                                     "-I" + str(root / "common/libs"), "-"], input=source, text=True, capture_output=True)
            self.assertEqual(result.returncode, 0, result.stderr)


if __name__ == "__main__":
    unittest.main()


class MainModeBoundsTests(unittest.TestCase):
    """The main-mode bounds order main-mode against sub-mode steps (§14)."""

    def test_neutral_without_a_sub_mode(self):
        base = Scenario()
        edited = replace(base.configuration, min_main_mode_steps=2, max_main_mode_steps=10)
        for mode in (0x01, 0x02, 0x03):
            values = config_values(replace(base, configuration=replace(edited, mode=mode)))
            self.assertEqual((values["creation_min_main_mode_steps"], values["creation_max_main_mode_steps"]),
                             (1, 1), f"mode 0x{mode:02x} exported the disabled controls' values")
        for mode in (0x12, 0x32, 0x23):
            values = config_values(replace(base, configuration=replace(edited, mode=mode)))
            self.assertEqual((values["creation_min_main_mode_steps"], values["creation_max_main_mode_steps"]),
                             (2, 10), f"mode 0x{mode:02x} lost the requested bounds")
